### ISSUE TITLE
增加点阵试图

### ISSUE THREAD

**Issue by aptexd** [zuoez02/siyuan-plugin-background-grid#1]
作者你好，十分感谢您在闲暇中为思源做出的插件系统以及众多插件
昨天了网格插件十分好用
想到了两需求
1. 增加点阵方式
2. 支持间距设置
不知实现是否麻烦，您酌情考虑
再次十分感谢您的付出

**Comment by B3000Kcn** [comment]
曾经挂件版插件市场里的背景方格插件是有颜色和大小设置的，现在正式版的却没了。但在介绍页却说是有这些功能的，而且我看了代码，应该也是做了相关的功能，只是不知为何无法找到入口。

**Comment by zuoez02** [comment]
![image](https://github.com/zuoez02/siyuan-plugin-background-grid/assets/4801955/706ade6c-fd40-45bb-bd11-087f71893cbb)
右上角找到它，可能隐藏在插件列表里了，点击出现设置按钮就可以设置了
@IRBG1997

**Comment by B3000Kcn** [comment]
@zuoez02 
可是我的插件列表里的确没有，在集市里的这个插件也是没有设置按钮的，重启和重装插件甚至思源都没用
![图片](https://github.com/zuoez02/siyuan-plugin-background-grid/assets/111612726/3053fe1e-9903-4512-8d36-93d390e31f31)
![图片](https://github.com/zuoez02/siyuan-plugin-background-grid/assets/111612726/be45109e-06bf-4bf7-915b-95348e53f6fb)

**Comment by zuoez02** [comment]
搞定了，等待新版本就可以了，发版包的问题。请等待1小时后市场应该就有新版本0.1.1了。
@aptexd 点阵已支持

**Comment by B3000Kcn** [comment]
@zuoez02 感谢
