### ISSUE TITLE
提点优化建议

### ISSUE THREAD

**Issue by MaxBill** [zuoez02/siyuan-plugin-background-grid#2]
1.颜色可以增加颜色选择器，直接点击选择，方便点

2.可以设置一张背景图片，然后图片的透明度可以设置

要是觉得建议可以希望采纳，要是不合理就忽略

**Comment by zuoez02** [comment]
第一点不错，我研究一下。 第二点使用插件“背景图片”吧，我这就不去实现了，打架

**Comment by zuoez02** [comment]
第一点不错，我研究一下。 第二点使用插件“背景图片”吧，我这就不去实现了，打架

**Comment by zuoez02** [comment]
已支持颜色选择器

**Comment by MaxBill** [comment]
> 第一点不错，我研究一下。 第二点使用插件“背景图片”吧，我这就不去实现了，打架

也是 ，好像有一个背景图的，感谢大佬的插件，赞
